# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# XDC: new/clock.xdc

# IP: ip/led_mem/led_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_mem || ORIG_REF_NAME==led_mem} -quiet] -quiet
